default:
  script_dir: "where_the_scripts_from_github_are_stored/"
  cd_file_foldername: "where_the_files_from_GEO_are_stored/"
  output_file_dir: "where_you_want_your_result_file/"
  cd_variant_statistics_filename: "variant_statistics.txt.gz"
  cd_dna_count_filepath: "MPRA_CD_DNA_bcreads.txt.gz" 
  bc_file_pattern: "Pooled_.*\\_bcreads.txt"
  read_file_function_scriptname: "reading_functions.R"
  reproducibility_function_scriptname: "reproducibility_plot_functions.R"
  create_count_matrix_functions_scriptname: "create_count_matrix_functions.R"
  cd_barcode_rda_filename: "GSE244011_RAW.tar"
  cd_mpra_output_file: "cd_mpra_result.tsv"
  cd_dna_count_file: "GSE244011_dnaMatrix.csv.gz"
  cd_rna_count_file: "GSE244011_rnaMatrix.csv.gz"
